services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      VITE_IPFS_BASE_URL: ${IPFS_BASE_URL:-http://127.0.0.1:8080/ipfs}

  ipfs:
    image: docker.io/ipfs/kubo:latest
    volumes:
      - ./ipfs/data:/import:ro
      - ./ipfs/init.sh:/container-init.d/init.sh:ro
    ports:
      - 8080:8080
    depends_on:
      - challenge2

  chain:
    network_mode: host
    build: chain
    ports:
      - 8545:8545
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY:-0x4b986c55ea9496ccf30b437bb4577e5c6003049f4ce399061f52e074e97b5b92}
      PRIVATE_KEY2: ${PRIVATE_KEY2:-0xc28a2a5b185d0abd05458437fd553204d3e922e030484527ed3fef74fbaab3ec}

  contract-tests:
    image: docker.io/apeworx/ape
    command: test
    volumes:
      - ./contract:/home/harambe/project:ro

  contract-deploy:
    network_mode: host
    image: docker.io/apeworx/ape
    command: run deploy-all --network ${NETWORK:-::node}
    volumes:
      - ./contract:/home/harambe/project
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY:-0x4b986c55ea9496ccf30b437bb4577e5c6003049f4ce399061f52e074e97b5b92}
      PRIVATE_KEY2: ${PRIVATE_KEY2:-0xc28a2a5b185d0abd05458437fd553204d3e922e030484527ed3fef74fbaab3ec}
      APE_ACCOUNTS_account1_PASSPHRASE: "12345678"
      APE_ACCOUNTS_account2_PASSPHRASE: "12345678"

  challenge2:
    build: ./challenge2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - 8081:80
    volumes:
      - ./challenge2:/var/www/html:ro
    depends_on:
      - challenge2-db
  challenge2-db:
    image: mysql:8.0.32-oracle
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes;
      - MYSQL_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_DATABASE=test
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./challenge2/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
